<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net472</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Humanizer" Version="3.0.10" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xbim.Geometry.Abstractions\Xbim.Geometry.Abstractions.csproj" />
    <ProjectReference Include="..\Xbim.Geometry.GeomService\Xbim.Geometry.GeomService.csproj" />
  </ItemGroup>

</Project>