<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<Platforms>AnyCPU;x64;x86</Platforms>
		<GeometryInteropDirectory>../Xbim.Geometry.Engine.Interop/bin/$(Configuration)/</GeometryInteropDirectory>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Platform)' == 'x64' Or '$(Platform)' == 'AnyCPU'">
		<RunSettingsFilePath>$(MSBuildProjectDirectory)\test.x64.runsettings</RunSettingsFilePath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Platform)' == 'x86'">
		<RunSettingsFilePath>$(MSBuildProjectDirectory)\test.x86.runsettings</RunSettingsFilePath>
	</PropertyGroup>

	<PropertyGroup>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	  <NoWarn>CS8602;CS8604</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="8.2.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="NetTopologySuite.IO.SpatiaLite" Version="2.0.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.abstractions" Version="2.0.3" />
		<PackageReference Include="Xunit.DependencyInjection.Logging" Version="9.0.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="TestFiles\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Xbim.ModelGeometry.Scene\Xbim.ModelGeometry.Scene.csproj">
			<Private>True</Private>
		</ProjectReference>
		<ProjectReference Include="..\Xbim.Tessellator\Xbim.Tessellator.csproj" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)'!=''">
		<Content Include="$(GeometryInteropDirectory)$(TargetFramework)\win-x86\*.*">
			<Link>win-x86\%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>false</Pack>
			<Visible>true</Visible>
		</Content>
		<Content Include="$(GeometryInteropDirectory)$(TargetFramework)\win-x64\*.*">
			<Link>win-x64\%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>false</Pack>
			<Visible>true</Visible>
		</Content>
		<!-- TODO: ARM-->
	</ItemGroup>
</Project>
