// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Extrema_POnCurv2d.hxx>

#include <gp_Pnt2d.hxx>
 

#define Pnt gp_Pnt2d
#define Pnt_hxx <gp_Pnt2d.hxx>
#define Extrema_Point Extrema_POnCurv2d
#define Extrema_Point_hxx <Extrema_POnCurv2d.hxx>
#include <Extrema_Point.gxx>

